# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe26cbb78c1b30ab7cd36216249004729663be41e9466f8d61501472093c5c6026b7164b2cae99769fe283e18d13e6372a15733e2a61e51596b75e1fb57b618

test:
  secret_key_base: 680afe489237cbe5d923cfc5bfc09c2b44ecd5629e802130c36522d979358da773c3dc236172feda90490bd25d2a2072b63a4f190eeb4b316b107f5ae79fafdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
